apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: prow
  name: tide
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::821278736125:role/aws_prod_eks_gitops_prow_pod_role # just a sample here, replace the account id.
