# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.

triggers:
  - repos:
      - awsgcr # replace by your own org/repo_name
    ignore_ok_to_test: false
    elide_skipped_contexts: false

lgtm:
  - repos:
      - awsgcr
    review_acts_as_lgtm: true

approve:
  - repos:
      - awsgcr
    require_self_approval: false
    lgtm_acts_as_approve: true

file_size_limit:
  awsgcr:
    additional_ignore_file_exts: []

config_updater:
  maps:
    # 加载 Prow config 本身配置文件
    prow/config.yaml: 
      name: config
    # 加载 Prow plugins 本身配置文件
    prow/plugins.yaml:
      name: plugins
    # 加载 /prow/config/label-config/labels.yaml 文件, PR会进行不同颜色配色
    prow/config/label-config/*:
      name: label-config
      clusters:
        default:
          - test-pods
    # 加载 /prow/config/aws-config/aws-deploy-config 文件, 进行AWS资源部署
    prow/config/aws-config/*:
      name: aws-deploy-config
      clusters:
        default:
          - test-pods
          - kube-deploy
    # 加载 /prow/config/kube-config/all 文件, 访问EKS集群的配置
    prow/config/kube-config/*:
      name: kube-cluster-config
      clusters:
        default:
          - test-pods
          - kube-deploy
    # 加载 /prow/config/kube-deploy.yaml 文件, 部署K8S资源
    prow/config/k8s-deploy.yaml:
      name: k8s-deploy-config
      clusters:
        default:
          - kube-deploy
    # 加载 /prow/jobs/ 里面所有文件，配置自定义脚本
    prow/jobs/**/*.yaml:
      name: job-config
      gzip: true
    # 加载 /prow/scripts/ 里面所有脚本
    prow/scripts/*:
      name: prow-ci-scripts
      clusters:
        default:
          - test-pods

plugins:
  awsgcr:
    plugins:
      - approve # Allow OWNERS to /approve
      - assign # Allow /assign and /cc
      # - blunderbuss # Auto-assign people
      - cat # /meow replies with cat pictures
      - dog # /woof replies with dog pictures
      # - goose # /honk replies with goose pictures
      - help # Support /help and /good-first-issue
      - hold # Support /hold to delay merge
      - label
      - lgtm # Allow /lgtm
      - lifecycle # Allow /lifecycle stale
      - override
      - owners-label
      - verify-owners
      - pony # /pony replies with pony pictures
      - size # Auto-label size of PR
      - skip # Allows cleaning up stale commit statuses
      - trigger # Allow people to configure CI jobs to /test
      - verify-owners # Validates OWNERS file changes in PRs.
      - welcome
      - retitle
      - weainformer # notify users when they are being requested to review a PR
      - wip # Auto-hold PRs with WIP in title
      - repo-permission-alert # notify to wea group when teams and members in repo got permission changes
      # - yuks # Let prow tell a /joke
  awsgcr/aws-infra:
    plugins:
      - config-updater

yaml-validator:
  awsgcr/aws-infra:
    - files: ^prow/jobs/.*\.yaml$
      type: prowjob
    - files: ^.*\.ya?ml$
      type: yamllint

welcome:
  - message_template: "Welcome @{{.AuthorLogin}}!"
 
