# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.

triggers:
  - repos:
      - awsgcr/aws-infra # replace by your own org/repo_name
    ignore_ok_to_test: false
    elide_skipped_contexts: false

lgtm:
  - repos:
      - awsgcr
    review_acts_as_lgtm: true

approve:
  - repos:
      - awsgcr
    require_self_approval: false
    lgtm_acts_as_approve: true

file_size_limit:
  awsgcr/aws-infra:
    additional_ignore_file_exts: []

config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
    prow/scripts/*:
      name: prow-ci-scripts
      clusters:
        default:
          - test-pods
    prow/config/label-config/*:
      name: label-config
      clusters:
        default:
          - test-pods
    prow/config/policy:
      name: ecr-pull-policy
      clusters:
        default:
          - test-pods
    prow/config/config.json:
      name: docker-config
      clusters:
        default:
          - test-pods
    app/template/dockerfile/*:
      name: dockerfile-template
      clusters:
        default:
          - test-pods
    prow/jobs/**/*.yaml:
      name: aws-infra-job-config
      gzip: true
    prow/config/kube-deploy.yaml:
      name: aws-infra-kube-deploy-config
      clusters:
        default:
          - kube-deploy

plugins:
  awsgcr:
    plugins:
      - approve # Allow OWNERS to /approve
      - assign # Allow /assign and /cc
      # - blunderbuss # Auto-assign people
      - cat # /meow replies with cat pictures
      - dog # /woof replies with dog pictures
      # - goose # /honk replies with goose pictures
      - help # Support /help and /good-first-issue
      - hold # Support /hold to delay merge
      - label
      - lgtm # Allow /lgtm
      - lifecycle # Allow /lifecycle stale
      - override
      - owners-label
      - verify-owners
      - pony # /pony replies with pony pictures
      - size # Auto-label size of PR
      - skip # Allows cleaning up stale commit statuses
      - trigger # Allow people to configure CI jobs to /test
      - verify-owners   # Validates OWNERS file changes in PRs.
      - welcome
      - retitle
      - weainformer # notify users when they are being requested to review a PR
      - wip # Auto-hold PRs with WIP in title
      - repo-permission-alert # notify to wea group when teams and members in repo got permission changes
      # - yuks # Let prow tell a /joke

# this is yaml-validator config
yaml-validator:
  devops/devops-infra:
    - files: ^prow/jobs/.*\.yaml$
      type: prowjob
    - files: ^.*\.ya?ml$
      type: yamllint

welcome:
  - message_template: "Welcome @{{.AuthorLogin}}! <br><br>It looks like this is your first PR to <a href='https://github.com/{{.Org}}/{{.Repo}}'>{{.Org}}/{{.Repo}}</a> 🎉. Please refer to our [pull request process documentation](https://git.k8s.io/community/contributors/guide/pull-requests.md) to help your PR have a smooth ride to approval. <br><br>You will be prompted by a bot to use commands during the review process. Do not be afraid to follow the prompts! It is okay to experiment. [Here is the bot commands documentation](https://go.k8s.io/bot-commands). <br><br>You can also check if {{.Org}}/{{.Repo}} has [its own contribution guidelines](https://github.com/{{.Org}}/{{.Repo}}/tree/master/CONTRIBUTING.md). <br><br>You may want to refer to our [testing guide](https://git.k8s.io/community/contributors/devel/sig-testing/testing.md) if you run into trouble with your tests not passing. <br><br>If you are having difficulty getting your pull request seen, please follow the [recommended escalation practices](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#why-is-my-pull-request-not-getting-reviewed). Also, for tips and tricks in the contribution process you may want to read the [Kubernetes contributor cheat sheet](https://git.k8s.io/community/contributors/guide/contributor-cheatsheet/README.md). We want to make sure your contribution gets all the attention it needs! <br><br>Thank you, and welcome to Kubernetes. :smiley:"